<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>API</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">API</h1>
<p class='attribute'><strong>测试人员 : </strong> Mongo</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-01-05 16:24:28</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:01.443802</p>
<p class='attribute'><strong>测试结果 : </strong> 共 17，通过 4，错误 13，通过率= 23.53%</p>

<p class='description'>API测试报告</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 23.53% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 4 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 17 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>test_invest.InvestTest</td>
    <td class="text-center">7</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">7</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',7)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_5</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_6</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_7</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_invest.py", line 28, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr class='passClass warning'>
    <td>test_login.TestLogin</td>
    <td class="text-center">4</td>
    <td class="text-center">4</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',4)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='pt2_1' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_1'>通过</button>
    <div id='div_pt2_1' class="collapse in" align="left">
    <pre>
    
pt2_1: 测试准备
response:  {
    "status": 0,
    "code": "20111",
    "data": null,
    "msg": "用户名或密码错误"
}
测试清除


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_2' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_2'>通过</button>
    <div id='div_pt2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_2'>通过</button>
    <div id='div_pt2_2' class="collapse in" align="left">
    <pre>
    
pt2_2: 测试准备
response:  {
    "status": 0,
    "code": "20111",
    "data": null,
    "msg": "用户名或密码错误"
}
测试清除


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_3' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_3'>通过</button>
    <div id='div_pt2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_3'>通过</button>
    <div id='div_pt2_3' class="collapse in" align="left">
    <pre>
    
pt2_3: 测试准备
response:  {
    "status": 0,
    "code": "20103",
    "data": null,
    "msg": "密码不能为空"
}
测试清除


    </pre>
    </div>
    </td>
</tr>

<tr id='pt2_4' class='hiddenRow'>
    <td class='passCase'><div class='testcase'>test_login_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_pt2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_pt2_4'>通过</button>
    <div id='div_pt2_4' class="collapse in" align="left">
    <pre>
    
pt2_4: 测试准备
response:  {
    "status": 0,
    "code": "20103",
    "data": null,
    "msg": "手机号不能为空"
}
测试清除


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>test_recharge.TestRecharge</td>
    <td class="text-center">5</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">5</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',5)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_1</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_recharge.py", line 29, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_2</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_recharge.py", line 29, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_3</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_recharge.py", line 29, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_4</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_4'>错误</button>
    <div id='div_ft3_4' class="collapse in" align="left">
    <pre>
    
ft3_4: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_recharge.py", line 29, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_5</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_5'>错误</button>
    <div id='div_ft3_5' class="collapse in" align="left">
    <pre>
    
ft3_5: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_recharge.py", line 29, in setUp
    self.mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>unittest.suite._ErrorHolder</td>
    <td class="text-center">1</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">1</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',1)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='errorCase'><div class='testcase'>TestRegister)</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: Traceback (most recent call last):
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\testcases\test_register.py", line 30, in setUpClass
    mysql = MysqlUtil()
  File "C:\Users\11857\Desktop\python12-api-test-master\python12-api-test-master\common\mysql_util.py", line 30, in __init__
    port=port, cursorclass=pymysql.cursors.DictCursor)
  File "C:\python\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 598, in connect
    self._request_authentication()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 862, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "C:\python\lib\site-packages\pymysql\connections.py", line 933, in _process_auth
    pkt = self._read_packet()
  File "C:\python\lib\site-packages\pymysql\connections.py", line 683, in _read_packet
    packet.check_error()
  File "C:\python\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\python\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '****'@'113.89.99.196' (using password: YES)")


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>17</td>
    <td>4</td>
    <td>0</td>
    <td>13</td>
    <td>通过率：23.53%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
